/*
 * palette.h - Tank Game Color Palette
 * 16-color indexed palette for Classic Mac (System 6-9)
 * Generated by export-sprites.js
 */

#ifndef PALETTE_H
#define PALETTE_H

/* RGB values (0-255) */
typedef struct { unsigned char r, g, b; } RGB8;

static const RGB8 gPalette[16] = {
    {   0,   0,   0 }, /* 0: transparent */
    {  26,  26,  26 }, /* 1: outline */
    {  51,  51,  51 }, /* 2: dark_gray */
    {  85,  85,  85 }, /* 3: mid_gray */
    { 119, 119, 119 }, /* 4: light_gray */
    { 153, 153, 153 }, /* 5: pale_gray */
    { 204,  34,  34 }, /* 6: red_dark */
    { 255,  68,  68 }, /* 7: red_bright */
    {  34, 170,  34 }, /* 8: green_dark */
    {  68, 255,  68 }, /* 9: green_bright */
    {  34, 102, 204 }, /* 10: blue_dark */
    {  68, 136, 255 }, /* 11: blue_bright */
    { 204, 170,  34 }, /* 12: yellow_dark */
    { 255, 221,  68 }, /* 13: yellow_bright */
    { 139, 115,  85 }, /* 14: brown */
    { 255, 255, 255 } /* 15: white */
};

/* Mac 16-bit RGB format for Color QuickDraw */
typedef struct { short value; unsigned short red, green, blue; } MacColorSpec;

static const MacColorSpec gMacPalette[16] = {
    { 0, 0x0000, 0x0000, 0x0000 },
    { 1, 0x1a1a, 0x1a1a, 0x1a1a },
    { 2, 0x3333, 0x3333, 0x3333 },
    { 3, 0x5555, 0x5555, 0x5555 },
    { 4, 0x7777, 0x7777, 0x7777 },
    { 5, 0x9999, 0x9999, 0x9999 },
    { 6, 0xcccc, 0x2222, 0x2222 },
    { 7, 0xffff, 0x4444, 0x4444 },
    { 8, 0x2222, 0xaaaa, 0x2222 },
    { 9, 0x4444, 0xffff, 0x4444 },
    { 10, 0x2222, 0x6666, 0xcccc },
    { 11, 0x4444, 0x8888, 0xffff },
    { 12, 0xcccc, 0xaaaa, 0x2222 },
    { 13, 0xffff, 0xdddd, 0x4444 },
    { 14, 0x8b8b, 0x7373, 0x5555 },
    { 15, 0xffff, 0xffff, 0xffff }
};

#endif /* PALETTE_H */
